[package]
name = "connector"
version = "0.1.0"
authors = ["ternocus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0.9.14"
openssl = { version = "0.10", features = ["vendored"] }
kafka = "0.8.0"